### ISSUE TITLE
Want to get data for Scanner connected to printer when scanned by Scanner

### ISSUE THREAD

**Issue by mehtahardikr** [star-micronics/StarXpand-SDK-Android#10]
I have Zebra scanner attached with printer usb ports. **DS 9308.**
I want to monitor that devcie for scanned data and i also want printer to print the receipt.
When scanner device scans data i want to retireve that data as well. Is there any way to do this.

## Your printer
- Model Names:
    *mC-Print3*
- Firmware Version:
    *3.5*
- Interface:
    *USB*

## Your development environment
ProductName:	macOS
ProductVersion:	12.6.3
BuildVersion:	21G419

## Additional context
I want to achieve something like  get data from the scanner attached to printer through USB and Printer is attached to Android device running on  Android OS  9 (Pie) and want to capture data scanned by Scanner without monitor input device as its creating memory issue if we monitor for more than 10 minutes.

**Comment by YuzoKato** [comment]
mC-Print3 supports USB HID class only. Please make sure that your scanner is HID class.

Then, you can use an event-based API to get the data read by the barcode reader.
When the barcode is read, the [onDataReceived](https://star-m.jp/products/s_print/sdk/starxpand/manual/en/android-kotlin-api-reference/stario10/input-device-delegate/on-data-received.html) method of the [InputDeviceDelegate](https://star-m.jp/products/s_print/sdk/starxpand/manual/en/android-kotlin-api-reference/stario10/input-device-delegate/index.html) class is called, and the barcode data can be obtained.
Refer to the [sample](https://github.com/star-micronics/StarXpand-SDK-Android/blob/main/app/src/main/java/com/starmicronics/starxpandsdk/MonitorActivity.kt) contained in the SDK as well.

**Comment by Tatsuki-Yamamoto2731** [comment]
I am closing this Issue. If you still have this issue, please reopen it.
