### ISSUE TITLE
Error: com.starmicronics.stario10.StarIO10IllegalHostDeviceStateException: Network unavailable

### ISSUE THREAD

**Issue by Dwikavindra** [star-micronics/StarXpand-SDK-Android#11]
## Description
Error: com.starmicronics.stario10.StarIO10IllegalHostDeviceStateException: Network unavailable. errorCode: NetworkUnavailable.
I am trying to search for printers in my current network that I have connected using LAN. However, this is not working using the example provided in this SDK. My device is already connected to the same WiFi Network. Does this error have something to do with the Network or is it something to do with my Android device? Other methods works fined and logs Discovery Finished after 10 seconds. This also occurs for react native star io 
@gare-bear @bandit-ibayashi 
## Your device where the bug occurs 
 - Device: 
    Xioami Pad 5
 - OS:
    Android 11

## Your printer
- Model Names:
     mC-Print3
- Firmware Version:
     3.0
- Interface:
    LAN/ Ethernet

## Your development environment
MacOS Monterey

## To Reproduce
1. Clone the repo
2. Launch on Android Studio
3. Navigate to Discovery 
4. Press Discovery with LAN checked

## Expected behavior
A log with Discovery Finished after 10 seconds

## Screenshots

<img width="1348" alt="Screen Shot 2023-05-09 at 13 52 01" src="https://github.com/star-micronics/StarXpand-SDK-Android/assets/71365618/a99dbd76-ffae-436c-a8fc-9acf8595a137">

## Additional context
Add any other context about the bug here.

**Comment by bandit-ibayashi** [comment]
@Dwikavindra From the error information you have provided, it is most likely that the host device is not connected to the network. [StarIO10IllegalDeviceStateException](https://star-m.jp/products/s_print/sdk/starxpand/manual/en/android-kotlin-api-reference/stario10/star-io10-illegal-device-state-exception/index.html) is thrown when the status of a host device is invalid, and [NetworkUnavailable](https://star-m.jp/products/s_print/sdk/starxpand/manual/en/android-kotlin-api-reference/stario10/star-io10-error-code/index.html#android-kotlin-star-io10-error-code-network-unavailable) means the network function of the host device cannot be used.

Just to be sure, could you check again that your Android device is connected to the network, e.g. by web browsing?
If you are correctly connected to the network, we would like you to try searching for the printer using our [StarPRNT SDK](https://play.google.com/store/apps/details?id=com.StarMicronics.StarIOSDK) app, followed by isolating this issue.

**Comment by Tatsuki-Yamamoto2731** [comment]
I am closing this Issue. If you still have this issue, please reopen it.
