### ISSUE TITLE
SDK does not print any text, only logo and QR code with TSP100III model via Bluetooth

### ISSUE THREAD

**Issue by LewisEKay** [star-micronics/StarXpand-SDK-Android#13]
## Description
A clear and concise description of what a bug is.

## Your device where the bug occurs 
 - Device: 
    Samsung S20 Ultra
    Samsung S10 Plus
 - OS:
    Android Version 11

## Your printer
- Model Names:
   TSP143IIIBI2
- Firmware Version:
    3.0
- Interface:
    Bluetooth

## Your development environment
The result of executing the command `ver` on Windows, `sw_vers` on macOS, `uname –a` on Linux, or these equivalent commands.

## To Reproduce
1. Download this repo
2. Connect to print and attempt to print using PrintingActivity
3. Machine will only print QR code and Star Logo

## Expected behavior
It should print the entire sample code incouding the plain t shirt, denim info, etc.

## Screenshots

![IMG_0655](https://github.com/star-micronics/StarXpand-SDK-Android/assets/30117245/8d86c19b-df92-485f-b701-2e7571966afc)

**Comment by alsedi** [comment]
I guess it is StarGraphic format and you need to pre-render the text and send it as an image. I have the same printer it never printed texts from starPRNT or starXpand SDKs.

**Comment by LewisEKay** [comment]
@alsedi it's weird it says the device is supported in the starXpand list and no where says about printing as an image. Not that I can see but yes this seems to be the case thank you.
