### ISSUE TITLE
Issue With printing Text

### ISSUE THREAD

**Issue by Mian-Taha** [star-micronics/StarXpand-SDK-Android#14]
## Description
.actionPrintText is not printing text

## Your device where the bug occurs 
 - Device: 
    *e.g. Samsung S21 *
 - OS:
    *e.g. Android 13.0*
 - Browser: 
    *e.g. google*
 - Version
    *e.g. 22*

## Your printer
- Model Names:
    *e.g. star TSP100III
- Firmware Version:
    *e.g. 
- Interface:
    *e.g. Ethernet*

## Your development environment
android Studio
## Additional context
other functions like actionPrintImage and actionPrintQRCode are working but .actionPrintText is not printing text nither  .actionPrintBarcode is giving any output on printing

**Comment by alsedi** [comment]
I believe the TSP100III series is limited to graphics printing only. You need to convert your text to an image.

**Comment by gare-bear** [comment]
> I believe the TSP100III series is limited to graphics printing only. You need to convert your text to an image.

This is correct. The TSP100III series is graphical only.
See issues #4 #5 #13 for more info
