### ISSUE TITLE
Support for the TSP100II

### ISSUE THREAD

**Issue by Quintarous** [star-micronics/StarXpand-SDK-Android#15]
## Description
Does the StarXpand SDK support the TSP100II printer? When calling `StarPrinter.openAsync` method on the TSP100II a `Not supported model` error occurs. I'm a little confused since on the [documentation site](https://star-m.jp/products/s_print/sdk/starxpand/manual/en/android-kotlin-api-reference/stario10/star-printer/open-async.html#android-kotlin-star-printer-open-async) it lists the `TSP100IIU+ as being supported. Perhaps it's a slightly different version? 

Anyway using the older StarPRNT SDK for calls to this printer is not possible since the older StarPRNT SDK doesn't work on Android 10+ due to [this](https://developer.android.com/about/versions/10/privacy/changes#usb-serial) security change in Android 10 requiring you to declare a permission to read a USB serial number.

## Your device where the bug occurs 
EloPOS Z10 running Elo's custom version of Android 10

## Your printer
The unit information sticker for our TSP100II printer we are testing on:
![image](https://github.com/star-micronics/StarXpand-SDK-Android/assets/67393057/fbbc7848-3e0d-4a88-8eb1-d3ea2cb6f256)

## Your development environment
ProductName:    macOS
ProductVersion: 13.4
BuildVersion:      22F66

**Comment by gare-bear** [comment]
@Quintarous this SDK does not support the TSP100II also known as the TSP100 ECO. 
I believe the TSP100II+ is a variant of the ECO offered exclusively in the EMEA region. 
I am not 100% sure because its not offered in the US/CA/MX regions where I am located. 

@David-SME @Lozrus is that right?
