### ISSUE TITLE
After discovery succesful of my Star printer model , my android app occuring below error. com.starmicronics.stario 10.stario 10 invalidoperationexception not opened error code none in kotlin. Kindly help me

### ISSUE THREAD

**Issue by abhishekcitytech** [star-micronics/StarXpand-SDK-Android#16]
After discovery succesful of my Star printer model , 

my android app occuring below error. com.starmicronics.stario 10.stario 10 invalidoperationexception not opened error code none in kotlin. 

Kindly help me

**Comment by gare-bear** [comment]
@abhishekcitytech please update your post to include everything mentioned in our bug report or question template.

The I can get back to you with some suggestions.

**Comment by Tatsuki-Yamamoto2731** [comment]
I am closing this Issue. If you still have this issue, please reopen it.
