### ISSUE TITLE
What should identifier ?

### ISSUE THREAD

**Issue by Ramandeep-android** [star-micronics/StarXpand-SDK-Android#2]
## Description
Need to print receipt on MPOP printer
## Your device where the bug occurs 
 - Device: 
    MPOP
 - OS:
   Android

## Your printer
- Model Names:
  MPOP
- Interface:
   Bluetooth

**Comment by bandit-ibayashi** [comment]
We would like you to refer our [API reference](https://star-m.jp/products/s_print/sdk/starxpand/manual/en/android-kotlin/api-reference/stario10/star-connection-settings/identifier.html).

If you get [StarPrinter](https://star-m.jp/products/s_print/sdk/starxpand/manual/en/android-kotlin/api-reference/stario10/star-printer/index.html#android-kotlin-star-printer) object by [StarDeviceDiscoveryManager](https://star-m.jp/products/s_print/sdk/starxpand/manual/en/android-kotlin/api-reference/stario10/star-device-discovery-manager/index.html#android-kotlin-star-device-discovery-manager) API, please specify this object. You don't need to specify manually.

When setting manually, specify the Bluetooth Address or Bluetooth Device Name printed on [Self-Printing](https://www.star-m.jp/products/s_print/mpop/manual/en/basicOperations/testPrint.htm).

**Comment by gare-bear** [comment]
@Ramandeep-android Closing this issue for now. 
Just comment if you're still having issues and we'll re-open it.
