### ISSUE TITLE
Keep Monitoring printer drains more battery of device ( android )

### ISSUE THREAD

**Issue by mehtahardikr** [star-micronics/StarXpand-SDK-Android#23]
## Description
As use case is something like that want to allow USB scanner to be connected to through printer ( in that case have to keep monitor printer ) 
It works while keep monitoring printer on. But, issue is like that it drains much battery of device ( android tablet ) 

Is there any way to make less use of battery while monitor printer ? 

## Your device where the bug occurs 
 - Device: 
    *Samsung Galaxy Tab X200*
 - OS:
    *Android 14*

## Your printer
- Model Names:
    *mC-Print3*
- Firmware Version:
    *3.5*
- Interface:
    *LAN*

## Additional context
Just wanted to find the solution for the better way to monitor printer as usb scanner could be connectted through.
But battery drain issue also happens here.

**Comment by Tatsuki-Yamamoto2731** [comment]
@mehtahardikr I’ｍ sorry, but I think it is difficult to reduce power consumption by modifying the app because 
Is it difficult to operate the tablet while charging it?

**Comment by Tatsuki-Yamamoto2731** [comment]
Not updated for more than 3 months, therefore I closed this issue.
