### ISSUE TITLE
No text being printed.

### ISSUE THREAD

**Issue by DarrenMiddleton** [star-micronics/StarXpand-SDK-Android#4]
Description
When using the demo app to print the example receipt the only information that is being printed is the logo and the QR code. No text is being printed.

 - Device: 
    Samsung tablet s8
 - OS:
    Android 12
 - Version
    1.0.1

Printer
- Model Names:
    TSP100IIILAN
- Interface:
    Ethernet

1. Run the demo app.
2. Try to print using the print activity.
3. Logo and QR code are only printed.

**Comment by DarrenMiddleton** [comment]
![PXL_20221104_161939023](https://user-images.githubusercontent.com/42702767/200026418-add610b5-2a8d-47b8-baaa-cd828c53342d.jpg)

**Comment by dimiitpk** [comment]
Same here

**Comment by nicolasfaume** [comment]
It seem this printer only support printing Bitmap.

**Comment by gare-bear** [comment]
@DarrenMiddleton @dimiitpk 
The TSP100III series is graphics-only, which was mentioned by @nicolasfaume.
