### ISSUE TITLE
Feature Request: Support Rust Programming

### ISSUE THREAD

**Issue by ekokurniadi** [star-micronics/StarXpand-SDK-Android#7]
I have a simple application windows which created using rust, and i have some problem to connect with star mpop printer, would you mind to add rust language for starXpand SDK please ?

**Comment by gare-bear** [comment]
@ekokurniadi No plans for rust support at the moment. What's the issue you're facing?

**Comment by ekokurniadi** [comment]
@gare-bear i have a flutter desktop windows application which have some features printing and i have problem when i use starMpop printer, on flutter desktop windows use c++ as native platform but i can use rust as alternative, but starXpand sdk not support both programming language

**Comment by Tatsuki-Yamamoto2731** [comment]
@ekokurniadi Unfortunately, as @gare-bear mentioned, we have no plan to support Rust so far. Sorry for any inconvenience.
I am closing this Issue, but we received your feedback.
