### ISSUE TITLE
SP700 does not print € and £ symbols

### ISSUE THREAD

**Issue by eosobande** [star-micronics/StarXpand-SDK-Android#8]
## Description
SP700 does not print certain currencies.

It prints $ and CA$ symbols correctly but replaces € with ¥, and £ with GB

## Your device where the bug occurs 
 - Device: Android
 - OS: Android 10

## Your printer
- Model Names: SP700
- Interface: LAN

**Comment by gare-bear** [comment]
@eosobande I'm looking into this. 
The XpandSDK does have an enum for CharacterEncodingType and this is what you would use to switch code pages giving tou access to different currency symbols. The constructor is private and I need to check why. I'll get back to you soon.

**Comment by gare-bear** [comment]
@eosobande I was able to print all the currency symbols with no code changes. 
I just added the symbols to `.actionPrintText("€ ¥ £")` and it worked.

Could you update your original post with the printers self-test?

**Comment by Tatsuki-Yamamoto2731** [comment]
I am closing this Issue. If you still have this issue, please reopen it.
