### ISSUE TITLE
Can we  Read Scanner data and Printing task  same time or keep scanner read running and when need of printer stop scanner listener and start printing

### ISSUE THREAD

**Issue by mehtahardikr** [star-micronics/StarXpand-SDK-Android#9]
## Description
I have Zebra scanner attahced with printer usb ports. DS 9308.  
I want to monitor that devcie for scanned data and i also want printer to print the receipt. but if i monitor for inputDeviceDelegate it listen for scanner data and after that i am goint to print as well. but it keep saying 

`com.starmicronics.stario10.StarIO10InUseException: The device is in use by another process. errorCode: None`
 
Can you provide the way to use like that.
Or anything that i am doing wrong then let me know the correct way. 
I am closing printer  and open again for printing purpose. but, its still says used by another process.

 - Device: 
    *Android Samsung galaxy tab A*
 - OS:
    *Android  9.0*
 

## printer
- Model Names:
    *mC-Print3*
- Firmware Version:
    *3.5*
- Interface:
    *Usb*

**Comment by gare-bear** [comment]
@mehtahardikr please follow our issue template and update your post with all the required info
